http_port 3128
acl registries dstdomain .npmjs.org .npmjs.com .yarnpkg.com .pypi.org .pythonhosted.org
acl SSL_ports port 443
acl CONNECT method CONNECT
http_access deny CONNECT !SSL_ports
http_access allow registries
http_access deny all
cache deny all
access_log stdio:/dev/stdout
